# ~/.tmuxinator/dev.yml

name: dev
root: ~/

windows:
  - editor:
      layout: main-vertical
      panes:
        - vim
        - guard
  - server: bundle exec rails s
  - logs: tail -f logs/development.log

