set nocompatible
filetype off

call plug#begin('~/.vim/plugged')
" Misc
Plug 'flazz/vim-colorschemes'
Plug 'itchyny/lightline.vim'
Plug 'mhinz/vim-startify'

" DEV Tools
Plug 'scrooloose/nerdtree'
Plug 'Xuyuanp/nerdtree-git-plugin'
Plug 'mileszs/ack.vim'
Plug 'vimwiki/vimwiki'
Plug 'vim-syntastic/syntastic'
Plug 'pangloss/vim-javascript'
Plug 'mxw/vim-jsx'
Plug 'kien/ctrlp.vim'
Plug 'majutsushi/tagbar'
Plug 'Shougo/vimproc.vim'
Plug 'Shougo/vimshell.vim'
Plug 'tpope/vim-fugitive'
Plug 'airblade/vim-gitgutter'
Plug 'mattn/webapi-vim'
Plug 'mattn/gist-vim'
Plug 'mtth/scratch.vim'
Plug 'elzr/vim-json'
Plug 'plasticboy/vim-markdown'
Plug 'tpope/vim-git'
Plug 'junegunn/fzf'
Plug 'MarcWeber/vim-addon-mw-utils'
Plug 'tomtom/tlib_vim'
Plug 'garbas/vim-snipmate'
Plug 'honza/vim-snippets'
Plug 'skywind3000/asyncrun.vim'
Plug 'MattesGroeger/vim-bookmarks'
Plug 'kien/tabman.vim'
Plug 'mbbill/undotree'
Plug 'airblade/vim-rooter'
Plug 'posva/vim-vue'
Plug 'fatih/vim-go'
Plug 'nickhutchinson/vim-cmake-syntax'
call plug#end()